spec:
  name: rs999-static-site
  region: nyc
  
  static_sites:
    - name: rs999-website
      github:
        repo: giriv11/rs999static
        branch: main
        deploy_on_push: true
      
      build_command: npm install && npm run build-css
      output_dir: /
      catchall_document: index.html
      error_document: 404.html
  
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
